package com.br.Enums;

public enum posicao {
    ATACANTE,
    SEGUNDO_ATACANTE,
    PONTA_ESQUERDA,
    PONTA_DIREITA,
    MEIA_ATACANTE,
    MEIA_CENTRAL,
    VOLANTE,
    ALA_DEFENSIVA_DIREITA,
    ALA_DEFENSIVA_ESQUERDA,
    LATERAL_ESQUERDO,
    LATERAL_DIREITO,
    ZAGUEIRO,
    GOLEIRO
}
